### ISSUE TITLE
Bug: Mobile layout overflow

### ISSUE THREAD

**Issue by Majorfi** [yearn/b2b-dashboard#148]
### What happened 🆘
On mobile, the layout is overflowing on the partner page because of the from/to/download buttons

### To Reproduce 🔂
Steps to reproduce the behavior: Visit a partner page on mobile

### More 🔎
- Browser: All

## Screenshots
<img width="439" alt="Capture d’écran 2023-03-17 à 12 19 56" src="https://user-images.githubusercontent.com/90963895/225890654-91c0ba66-4021-488b-98ac-1964368e5865.png">
<img width="442" alt="Capture d’écran 2023-03-17 à 12 19 47" src="https://user-images.githubusercontent.com/90963895/225890657-c0d51762-6b6b-49f6-9515-8aa1b582e046.png">

**Comment by 0xMirim** [comment]
This is technically solved awaiting merge of #151 that also now includes these changes. I reviewed and approved them on develop. I will officially close this when PR 151 is merged into main
