### ISSUE TITLE
Bug: Mobile numbers shrink

### ISSUE THREAD

**Issue by Majorfi** [yearn/b2b-dashboard#149]
### What happened 🆘
On mobile the partners numbers are shrinked way too much because of a `w-[60%]` and a `flex/justify-between`. Grid could be a better alternative here to keep spacing and break it easily. Margin Y should also be adapted

### To Reproduce 🔂
Steps to reproduce the behavior: Visit partner page on mobile

### More 🔎
- Browser: All

## Screenshots
<img width="399" alt="Capture d’écran 2023-03-17 à 12 21 16" src="https://user-images.githubusercontent.com/90963895/225891171-5f80abda-271d-46f1-8ad6-0031d5be0662.png">

**Comment by 0xMirim** [comment]
This fix has been merged into main
